[2024-04-13T00:00:07.265+0000] {processor.py:161} INFO - Started process (PID=56070) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:00:07.267+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:00:07.270+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:00:07.270+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:00:07.329+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:00:07.324+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:00:07.331+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:00:07.353+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.093 seconds
[2024-04-13T00:00:37.633+0000] {processor.py:161} INFO - Started process (PID=56126) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:00:37.635+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:00:37.637+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:00:37.637+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:00:37.697+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:00:37.691+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:00:37.698+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:00:37.723+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.093 seconds
[2024-04-13T00:01:08.439+0000] {processor.py:161} INFO - Started process (PID=56181) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:01:08.441+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:01:08.443+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:01:08.443+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:01:08.508+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:01:08.502+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:01:08.509+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:01:08.532+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.097 seconds
[2024-04-13T00:01:38.881+0000] {processor.py:161} INFO - Started process (PID=56237) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:01:38.882+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:01:38.885+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:01:38.884+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:01:38.946+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:01:38.940+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:01:38.948+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:01:38.971+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.094 seconds
[2024-04-13T00:02:09.258+0000] {processor.py:161} INFO - Started process (PID=56292) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:02:09.260+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:02:09.262+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:02:09.262+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:02:09.323+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:02:09.318+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:02:09.324+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:02:09.347+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.092 seconds
[2024-04-13T00:02:39.492+0000] {processor.py:161} INFO - Started process (PID=56347) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:02:39.493+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:02:39.496+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:02:39.495+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:02:39.561+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:02:39.554+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:02:39.568+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:02:39.602+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.115 seconds
[2024-04-13T00:03:09.780+0000] {processor.py:161} INFO - Started process (PID=56402) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:03:09.781+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:03:09.784+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:03:09.783+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:03:09.846+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:03:09.840+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:03:09.848+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:03:09.873+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.096 seconds
[2024-04-13T00:03:39.986+0000] {processor.py:161} INFO - Started process (PID=56457) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:03:39.987+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:03:39.989+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:03:39.989+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:03:40.051+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:03:40.046+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:03:40.053+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:03:40.075+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.093 seconds
[2024-04-13T00:04:10.714+0000] {processor.py:161} INFO - Started process (PID=56512) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:04:10.715+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:04:10.718+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:04:10.717+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:04:10.779+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:04:10.772+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:04:10.781+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:04:10.804+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.094 seconds
[2024-04-13T00:04:40.913+0000] {processor.py:161} INFO - Started process (PID=56567) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:04:40.915+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:04:40.919+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:04:40.918+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:04:40.996+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:04:40.992+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:04:40.998+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:04:41.026+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.117 seconds
[2024-04-13T00:05:11.232+0000] {processor.py:161} INFO - Started process (PID=56622) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:05:11.234+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:05:11.237+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:05:11.237+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:05:11.298+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:05:11.293+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:05:11.299+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:05:11.322+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.093 seconds
[2024-04-13T00:05:41.808+0000] {processor.py:161} INFO - Started process (PID=56677) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:05:41.810+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:05:41.814+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:05:41.813+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:05:41.883+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:05:41.877+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:05:41.885+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:05:41.907+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.103 seconds
[2024-04-13T00:06:12.547+0000] {processor.py:161} INFO - Started process (PID=56732) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:06:12.548+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:06:12.551+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:06:12.550+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:06:12.611+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:06:12.605+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:06:12.612+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:06:12.634+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.091 seconds
[2024-04-13T00:06:42.864+0000] {processor.py:161} INFO - Started process (PID=56787) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:06:42.866+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:06:42.868+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:06:42.868+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:06:42.929+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:06:42.923+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:06:42.932+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:06:42.956+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.095 seconds
[2024-04-13T00:07:13.306+0000] {processor.py:161} INFO - Started process (PID=56843) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:07:13.307+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:07:13.310+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:07:13.310+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:07:13.370+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:07:13.365+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:07:13.372+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:07:13.394+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.092 seconds
[2024-04-13T00:07:43.782+0000] {processor.py:161} INFO - Started process (PID=56898) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:07:43.783+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:07:43.786+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:07:43.785+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:07:43.849+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:07:43.843+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:07:43.850+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:07:43.874+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.096 seconds
[2024-04-13T00:08:14.067+0000] {processor.py:161} INFO - Started process (PID=56953) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:08:14.068+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:08:14.071+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:08:14.071+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:08:14.148+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:08:14.143+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:08:14.150+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:08:14.174+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.111 seconds
[2024-04-13T00:08:44.346+0000] {processor.py:161} INFO - Started process (PID=57008) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:08:44.347+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:08:44.350+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:08:44.349+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:08:44.449+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:08:44.444+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:08:44.451+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:08:44.500+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.159 seconds
[2024-04-13T00:09:14.592+0000] {processor.py:161} INFO - Started process (PID=57063) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:09:14.594+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:09:14.596+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:09:14.596+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:09:14.671+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:09:14.666+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:09:14.673+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:09:14.697+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.109 seconds
[2024-04-13T00:09:45.609+0000] {processor.py:161} INFO - Started process (PID=57118) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:09:45.610+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:09:45.612+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:09:45.612+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:09:45.675+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:09:45.670+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:09:45.676+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:09:45.713+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.108 seconds
[2024-04-13T00:10:15.858+0000] {processor.py:161} INFO - Started process (PID=57173) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:10:15.859+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:10:15.863+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:10:15.862+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:10:15.934+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:10:15.928+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:10:15.936+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:10:15.959+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.104 seconds
[2024-04-13T00:10:46.259+0000] {processor.py:161} INFO - Started process (PID=57228) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:10:46.260+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:10:46.263+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:10:46.262+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:10:46.336+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:10:46.330+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:10:46.338+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:10:46.362+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.106 seconds
[2024-04-13T00:11:16.510+0000] {processor.py:161} INFO - Started process (PID=57283) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:11:16.511+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:11:16.514+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:11:16.514+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:11:16.584+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:11:16.578+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:11:16.586+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:11:16.614+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.108 seconds
[2024-04-13T00:11:46.829+0000] {processor.py:161} INFO - Started process (PID=57338) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:11:46.830+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:11:46.833+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:11:46.833+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:11:46.905+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:11:46.899+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:11:46.906+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:11:46.934+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.108 seconds
[2024-04-13T00:12:17.223+0000] {processor.py:161} INFO - Started process (PID=57393) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:12:17.224+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:12:17.227+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:12:17.226+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:12:17.310+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:12:17.304+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:12:17.313+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:12:17.341+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.125 seconds
[2024-04-13T00:12:47.756+0000] {processor.py:161} INFO - Started process (PID=57448) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:12:47.757+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:12:47.759+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:12:47.759+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:12:47.819+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:12:47.814+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:12:47.821+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:12:47.843+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.091 seconds
[2024-04-13T00:13:18.220+0000] {processor.py:161} INFO - Started process (PID=57503) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:13:18.221+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:13:18.224+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:13:18.224+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:13:18.285+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:13:18.279+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:13:18.286+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:13:18.309+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.093 seconds
[2024-04-13T00:13:49.152+0000] {processor.py:161} INFO - Started process (PID=57558) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:13:49.153+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:13:49.156+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:13:49.155+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:13:49.225+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:13:49.218+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:13:49.227+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:13:49.252+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.103 seconds
[2024-04-13T00:14:19.472+0000] {processor.py:161} INFO - Started process (PID=57613) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:14:19.474+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:14:19.477+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:14:19.476+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:14:19.548+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:14:19.542+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:14:19.550+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:14:19.575+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.106 seconds
[2024-04-13T00:14:49.861+0000] {processor.py:161} INFO - Started process (PID=57668) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:14:49.863+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:14:49.866+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:14:49.865+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:14:49.930+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:14:49.924+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:14:49.931+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:14:49.955+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.097 seconds
[2024-04-13T00:15:20.263+0000] {processor.py:161} INFO - Started process (PID=57723) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:15:20.264+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:15:20.267+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:15:20.266+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:15:20.328+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:15:20.322+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:15:20.329+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:15:20.352+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.092 seconds
[2024-04-13T00:15:50.638+0000] {processor.py:161} INFO - Started process (PID=57778) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:15:50.640+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:15:50.642+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:15:50.642+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:15:50.703+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:15:50.699+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:15:50.705+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:15:50.731+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.096 seconds
[2024-04-13T00:16:20.932+0000] {processor.py:161} INFO - Started process (PID=57833) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:16:20.933+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:16:20.936+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:16:20.935+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:16:20.999+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:16:20.993+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:16:21.001+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:16:21.024+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.096 seconds
[2024-04-13T00:16:51.331+0000] {processor.py:161} INFO - Started process (PID=57888) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:16:51.332+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:16:51.335+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:16:51.334+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:16:51.393+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:16:51.388+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:16:51.394+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:16:51.422+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.095 seconds
[2024-04-13T00:17:21.784+0000] {processor.py:161} INFO - Started process (PID=57943) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:17:21.785+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:17:21.788+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:17:21.788+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:17:21.865+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:17:21.859+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:17:21.867+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:17:21.890+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.109 seconds
[2024-04-13T00:17:52.280+0000] {processor.py:161} INFO - Started process (PID=57999) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:17:52.282+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:17:52.284+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:17:52.284+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:17:52.348+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:17:52.343+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:17:52.350+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:17:52.373+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.097 seconds
[2024-04-13T00:18:22.914+0000] {processor.py:161} INFO - Started process (PID=58054) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:18:22.916+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:18:22.918+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:18:22.918+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:18:22.981+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:18:22.975+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:18:22.982+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:18:23.011+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.100 seconds
[2024-04-13T00:18:53.131+0000] {processor.py:161} INFO - Started process (PID=58109) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:18:53.132+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:18:53.135+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:18:53.135+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:18:53.195+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:18:53.189+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:18:53.197+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:18:53.220+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.093 seconds
[2024-04-13T00:19:23.495+0000] {processor.py:161} INFO - Started process (PID=58164) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:19:23.496+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:19:23.499+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:19:23.499+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:19:23.571+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:19:23.566+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:19:23.573+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:19:23.599+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.109 seconds
[2024-04-13T00:19:53.780+0000] {processor.py:161} INFO - Started process (PID=58219) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:19:53.781+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:19:53.784+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:19:53.783+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:19:53.854+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:19:53.848+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:19:53.855+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:19:53.878+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.104 seconds
[2024-04-13T00:20:24.017+0000] {processor.py:161} INFO - Started process (PID=58273) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:20:24.018+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:20:24.021+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:20:24.021+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:20:24.087+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:20:24.081+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:20:24.089+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:20:24.118+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.107 seconds
[2024-04-13T00:20:54.484+0000] {processor.py:161} INFO - Started process (PID=58329) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:20:54.485+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:20:54.488+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:20:54.488+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:20:54.544+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:20:54.539+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:20:54.546+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:20:54.568+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.087 seconds
[2024-04-13T00:21:25.286+0000] {processor.py:161} INFO - Started process (PID=58384) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:21:25.287+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:21:25.291+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:21:25.290+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:21:25.357+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:21:25.351+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:21:25.359+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:21:25.380+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.100 seconds
[2024-04-13T00:21:55.737+0000] {processor.py:161} INFO - Started process (PID=58439) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:21:55.739+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:21:55.741+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:21:55.741+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:21:55.817+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:21:55.812+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:21:55.819+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:21:55.842+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.108 seconds
[2024-04-13T00:22:26.261+0000] {processor.py:161} INFO - Started process (PID=58494) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:22:26.262+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:22:26.265+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:22:26.264+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:22:26.333+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:22:26.328+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:22:26.336+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:22:26.363+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.107 seconds
[2024-04-13T00:22:56.628+0000] {processor.py:161} INFO - Started process (PID=58550) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:22:56.630+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:22:56.633+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:22:56.632+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:22:56.705+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:22:56.700+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:22:56.707+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:22:56.747+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.122 seconds
[2024-04-13T00:23:27.300+0000] {processor.py:161} INFO - Started process (PID=58605) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:23:27.302+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:23:27.304+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:23:27.304+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:23:27.372+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:23:27.367+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:23:27.374+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:23:27.396+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.099 seconds
[2024-04-13T00:23:58.206+0000] {processor.py:161} INFO - Started process (PID=58660) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:23:58.207+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:23:58.210+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:23:58.210+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:23:58.278+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:23:58.271+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:23:58.281+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:23:58.305+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.103 seconds
[2024-04-13T00:24:28.546+0000] {processor.py:161} INFO - Started process (PID=58715) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:24:28.547+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:24:28.550+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:24:28.549+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:24:28.635+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:24:28.630+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:24:28.638+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:24:28.674+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.133 seconds
[2024-04-13T00:24:59.465+0000] {processor.py:161} INFO - Started process (PID=58770) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:24:59.466+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:24:59.469+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:24:59.468+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:24:59.551+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:24:59.545+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:24:59.553+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:24:59.580+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.118 seconds
[2024-04-13T00:25:30.101+0000] {processor.py:161} INFO - Started process (PID=58826) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:25:30.102+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:25:30.105+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:25:30.105+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:25:30.164+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:25:30.158+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:25:30.166+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:25:30.189+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.092 seconds
[2024-04-13T00:26:00.320+0000] {processor.py:161} INFO - Started process (PID=58881) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:26:00.321+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:26:00.324+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:26:00.323+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:26:00.385+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:26:00.379+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:26:00.386+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:26:00.409+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.092 seconds
[2024-04-13T00:26:30.973+0000] {processor.py:161} INFO - Started process (PID=58936) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:26:30.974+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:26:30.977+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:26:30.977+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:26:31.056+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:26:31.046+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:26:31.059+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:26:31.085+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.115 seconds
[2024-04-13T00:27:01.841+0000] {processor.py:161} INFO - Started process (PID=58997) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:27:01.843+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:27:01.846+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:27:01.845+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:27:01.930+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:27:01.925+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:27:01.932+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:27:01.954+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.117 seconds
[2024-04-13T00:27:32.160+0000] {processor.py:161} INFO - Started process (PID=59052) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:27:32.161+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:27:32.164+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:27:32.163+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:27:32.226+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:27:32.219+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:27:32.227+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:27:32.250+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.093 seconds
[2024-04-13T00:28:02.594+0000] {processor.py:161} INFO - Started process (PID=59107) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:28:02.596+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:28:02.598+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:28:02.598+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:28:02.658+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:28:02.653+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:28:02.660+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:28:02.687+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.096 seconds
[2024-04-13T00:28:33.166+0000] {processor.py:161} INFO - Started process (PID=59162) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:28:33.167+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:28:33.170+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:28:33.169+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:28:33.234+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:28:33.228+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:28:33.235+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:28:33.258+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.095 seconds
[2024-04-13T00:29:03.553+0000] {processor.py:161} INFO - Started process (PID=59217) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:29:03.554+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:29:03.557+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:29:03.556+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:29:03.613+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:29:03.608+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:29:03.614+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:29:03.642+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.092 seconds
[2024-04-13T00:29:34.052+0000] {processor.py:161} INFO - Started process (PID=59273) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:29:34.054+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:29:34.057+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:29:34.056+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:29:34.120+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:29:34.114+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:29:34.122+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:29:34.144+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.097 seconds
[2024-04-13T00:30:05.008+0000] {processor.py:161} INFO - Started process (PID=59328) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:30:05.010+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:30:05.013+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:30:05.012+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:30:05.091+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:30:05.087+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:30:05.093+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:30:05.120+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.117 seconds
[2024-04-13T00:30:35.298+0000] {processor.py:161} INFO - Started process (PID=59383) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:30:35.299+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:30:35.302+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:30:35.302+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:30:35.363+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:30:35.357+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:30:35.365+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:30:35.390+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.095 seconds
[2024-04-13T00:31:05.612+0000] {processor.py:161} INFO - Started process (PID=59438) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:31:05.614+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:31:05.616+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:31:05.616+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:31:05.683+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:31:05.678+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:31:05.685+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:31:05.706+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.099 seconds
[2024-04-13T00:31:35.987+0000] {processor.py:161} INFO - Started process (PID=59493) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:31:35.988+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:31:35.991+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:31:35.991+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:31:36.070+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:31:36.063+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:31:36.072+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:31:36.113+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.130 seconds
[2024-04-13T00:32:06.382+0000] {processor.py:161} INFO - Started process (PID=59548) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:32:06.384+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:32:06.386+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:32:06.386+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:32:06.451+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:32:06.445+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:32:06.452+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:32:06.492+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.114 seconds
[2024-04-13T00:32:36.781+0000] {processor.py:161} INFO - Started process (PID=59603) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:32:36.782+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:32:36.785+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:32:36.785+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:32:36.878+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:32:36.872+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:32:36.880+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:32:36.902+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.125 seconds
[2024-04-13T00:33:07.242+0000] {processor.py:161} INFO - Started process (PID=59658) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:33:07.244+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:33:07.246+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:33:07.246+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:33:07.317+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:33:07.312+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:33:07.320+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:33:07.343+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.105 seconds
[2024-04-13T00:33:38.163+0000] {processor.py:161} INFO - Started process (PID=59713) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:33:38.164+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:33:38.167+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:33:38.166+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:33:38.234+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:33:38.227+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:33:38.236+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:33:38.263+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.103 seconds
[2024-04-13T00:34:09.185+0000] {processor.py:161} INFO - Started process (PID=59768) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:34:09.187+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:34:09.189+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:34:09.189+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:34:09.258+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:34:09.252+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:34:09.259+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:34:09.281+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.100 seconds
[2024-04-13T00:34:40.043+0000] {processor.py:161} INFO - Started process (PID=59823) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:34:40.044+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:34:40.047+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:34:40.047+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:34:40.115+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:34:40.109+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:34:40.118+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:34:40.144+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.106 seconds
[2024-04-13T00:35:11.011+0000] {processor.py:161} INFO - Started process (PID=59878) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:35:11.013+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:35:11.016+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:35:11.016+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:35:11.119+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:35:11.114+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:35:11.122+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:35:11.148+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.143 seconds
[2024-04-13T00:35:41.331+0000] {processor.py:161} INFO - Started process (PID=59933) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:35:41.333+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:35:41.337+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:35:41.336+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:35:41.430+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:35:41.424+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:35:41.432+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:35:41.468+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.142 seconds
[2024-04-13T00:36:11.623+0000] {processor.py:161} INFO - Started process (PID=59988) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:36:11.625+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:36:11.627+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:36:11.627+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:36:11.695+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:36:11.689+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:36:11.697+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:36:11.722+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.104 seconds
[2024-04-13T00:36:41.950+0000] {processor.py:161} INFO - Started process (PID=60043) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:36:41.952+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:36:41.956+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:36:41.955+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:36:42.030+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:36:42.024+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:36:42.031+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:36:42.057+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.113 seconds
[2024-04-13T00:37:12.245+0000] {processor.py:161} INFO - Started process (PID=60098) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:37:12.247+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:37:12.249+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:37:12.249+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:37:12.314+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:37:12.309+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:37:12.316+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:37:12.342+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.103 seconds
[2024-04-13T00:37:42.426+0000] {processor.py:161} INFO - Started process (PID=60153) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:37:42.428+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:37:42.431+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:37:42.430+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:37:42.498+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:37:42.492+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:37:42.500+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:37:42.525+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.105 seconds
[2024-04-13T00:38:12.929+0000] {processor.py:161} INFO - Started process (PID=60208) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:38:12.930+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:38:12.933+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:38:12.933+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:38:13.000+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:38:12.994+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:38:13.003+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:38:13.029+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.105 seconds
[2024-04-13T00:38:43.642+0000] {processor.py:161} INFO - Started process (PID=60263) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:38:43.644+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:38:43.648+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:38:43.647+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:38:43.728+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:38:43.722+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:38:43.730+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:38:43.752+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.115 seconds
[2024-04-13T00:39:14.403+0000] {processor.py:161} INFO - Started process (PID=60318) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:39:14.404+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:39:14.407+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:39:14.406+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:39:14.484+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:39:14.478+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:39:14.487+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:39:14.516+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.119 seconds
[2024-04-13T00:39:44.683+0000] {processor.py:161} INFO - Started process (PID=60373) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:39:44.685+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:39:44.687+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:39:44.687+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:39:44.777+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:39:44.772+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:39:44.779+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:39:44.807+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.129 seconds
[2024-04-13T00:40:14.909+0000] {processor.py:161} INFO - Started process (PID=60428) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:40:14.910+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:40:14.912+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:40:14.912+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:40:15.000+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:40:14.995+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:40:15.003+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:40:15.031+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.128 seconds
[2024-04-13T00:40:45.873+0000] {processor.py:161} INFO - Started process (PID=60483) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:40:45.874+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:40:45.878+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:40:45.877+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:40:45.972+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:40:45.964+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:40:45.975+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:40:46.027+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.160 seconds
[2024-04-13T00:41:16.601+0000] {processor.py:161} INFO - Started process (PID=60537) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:41:16.625+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:41:16.633+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:41:16.632+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:41:16.823+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:41:16.791+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:41:16.840+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:41:16.905+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.310 seconds
[2024-04-13T00:41:47.326+0000] {processor.py:161} INFO - Started process (PID=60592) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:41:47.327+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:41:47.331+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:41:47.331+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:41:47.418+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:41:47.411+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:41:47.420+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:41:47.446+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.125 seconds
[2024-04-13T00:42:17.969+0000] {processor.py:161} INFO - Started process (PID=60647) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:42:17.970+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:42:17.974+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:42:17.973+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:42:18.056+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:42:18.051+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:42:18.058+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:42:18.089+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.127 seconds
[2024-04-13T00:42:48.600+0000] {processor.py:161} INFO - Started process (PID=60702) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:42:48.601+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:42:48.604+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:42:48.604+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:42:48.674+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:42:48.668+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:42:48.677+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:42:48.701+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.106 seconds
[2024-04-13T00:43:19.353+0000] {processor.py:161} INFO - Started process (PID=60757) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:43:19.354+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:43:19.357+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:43:19.356+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:43:19.425+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:43:19.420+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:43:19.427+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:43:19.452+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.104 seconds
[2024-04-13T00:43:49.878+0000] {processor.py:161} INFO - Started process (PID=60812) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:43:49.880+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:43:49.883+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:43:49.883+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:43:49.949+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:43:49.944+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:43:49.951+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:43:49.977+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.103 seconds
[2024-04-13T00:44:20.870+0000] {processor.py:161} INFO - Started process (PID=60867) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:44:20.871+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:44:20.874+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:44:20.874+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:44:20.949+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:44:20.943+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:44:20.951+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:44:20.979+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.115 seconds
[2024-04-13T00:44:51.262+0000] {processor.py:161} INFO - Started process (PID=60922) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:44:51.263+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:44:51.266+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:44:51.266+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:44:51.339+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:44:51.333+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:44:51.341+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:44:51.363+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.106 seconds
[2024-04-13T00:45:21.480+0000] {processor.py:161} INFO - Started process (PID=60977) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:45:21.481+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:45:21.484+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:45:21.483+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:45:21.561+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:45:21.555+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:45:21.564+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:45:21.591+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.116 seconds
[2024-04-13T00:45:51.989+0000] {processor.py:161} INFO - Started process (PID=61032) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:45:51.991+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:45:51.993+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:45:51.993+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:45:52.063+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:45:52.058+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:45:52.066+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:45:52.090+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.106 seconds
[2024-04-13T00:46:22.724+0000] {processor.py:161} INFO - Started process (PID=61087) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:46:22.725+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:46:22.728+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:46:22.727+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:46:22.800+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:46:22.796+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:46:22.802+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:46:22.826+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.108 seconds
[2024-04-13T00:46:53.747+0000] {processor.py:161} INFO - Started process (PID=61142) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:46:53.749+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:46:53.752+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:46:53.752+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:46:53.833+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:46:53.829+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:46:53.836+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:46:53.860+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.120 seconds
[2024-04-13T00:47:24.555+0000] {processor.py:161} INFO - Started process (PID=61197) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:47:24.557+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:47:24.560+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:47:24.560+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:47:24.638+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:47:24.632+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:47:24.640+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:47:24.674+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.124 seconds
[2024-04-13T00:47:55.014+0000] {processor.py:161} INFO - Started process (PID=61252) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:47:55.015+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:47:55.019+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:47:55.019+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:47:55.101+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:47:55.095+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:47:55.103+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:47:55.130+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.122 seconds
[2024-04-13T00:48:25.804+0000] {processor.py:161} INFO - Started process (PID=61307) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:48:25.806+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:48:25.809+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:48:25.808+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:48:25.880+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:48:25.874+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:48:25.883+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:48:25.907+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.110 seconds
[2024-04-13T00:48:56.579+0000] {processor.py:161} INFO - Started process (PID=61362) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:48:56.581+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:48:56.584+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:48:56.583+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:48:56.667+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:48:56.662+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:48:56.669+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:48:56.693+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.120 seconds
[2024-04-13T00:49:27.330+0000] {processor.py:161} INFO - Started process (PID=61416) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:49:27.332+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:49:27.335+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:49:27.334+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:49:27.405+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:49:27.400+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:49:27.407+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:49:27.437+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.112 seconds
[2024-04-13T00:49:58.215+0000] {processor.py:161} INFO - Started process (PID=61471) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:49:58.217+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:49:58.220+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:49:58.219+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:49:58.292+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:49:58.287+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:49:58.294+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:49:58.323+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.115 seconds
[2024-04-13T00:50:28.425+0000] {processor.py:161} INFO - Started process (PID=61526) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:50:28.427+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:50:28.431+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:50:28.430+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:50:28.510+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:50:28.506+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:50:28.512+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:50:28.544+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.127 seconds
[2024-04-13T00:50:58.720+0000] {processor.py:161} INFO - Started process (PID=61581) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:50:58.723+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:50:58.727+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:50:58.726+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:50:58.804+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:50:58.799+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:50:58.807+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:50:58.842+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.127 seconds
[2024-04-13T00:51:28.970+0000] {processor.py:161} INFO - Started process (PID=61636) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:51:28.972+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:51:28.976+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:51:28.976+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:51:29.048+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:51:29.044+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:51:29.051+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:51:29.077+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.114 seconds
[2024-04-13T00:51:59.464+0000] {processor.py:161} INFO - Started process (PID=61691) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:51:59.466+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:51:59.470+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:51:59.469+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:51:59.567+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:51:59.562+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:51:59.569+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:51:59.591+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.133 seconds
[2024-04-13T00:52:29.871+0000] {processor.py:161} INFO - Started process (PID=61746) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:52:29.872+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:52:29.875+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:52:29.874+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:52:29.950+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:52:29.944+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:52:29.952+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:52:29.978+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.113 seconds
[2024-04-13T00:53:00.254+0000] {processor.py:161} INFO - Started process (PID=61801) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:53:00.256+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:53:00.259+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:53:00.258+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:53:00.339+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:53:00.334+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:53:00.341+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:53:00.379+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.133 seconds
[2024-04-13T00:53:30.505+0000] {processor.py:161} INFO - Started process (PID=61857) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:53:30.507+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:53:30.510+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:53:30.509+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:53:30.578+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:53:30.572+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:53:30.580+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:53:30.608+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.109 seconds
[2024-04-13T00:54:00.783+0000] {processor.py:161} INFO - Started process (PID=61912) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:54:00.785+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:54:00.788+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:54:00.788+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:54:00.869+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:54:00.865+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:54:00.871+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:54:00.900+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.124 seconds
[2024-04-13T00:54:31.066+0000] {processor.py:161} INFO - Started process (PID=61967) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:54:31.067+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:54:31.070+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:54:31.069+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:54:31.141+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:54:31.136+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:54:31.143+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:54:31.171+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.112 seconds
[2024-04-13T00:55:01.311+0000] {processor.py:161} INFO - Started process (PID=62022) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:55:01.312+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:55:01.315+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:55:01.314+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:55:01.383+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:55:01.378+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:55:01.385+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:55:01.410+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.106 seconds
[2024-04-13T00:55:31.657+0000] {processor.py:161} INFO - Started process (PID=62078) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:55:31.659+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:55:31.661+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:55:31.661+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:55:31.736+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:55:31.731+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:55:31.738+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:55:31.761+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.109 seconds
[2024-04-13T00:56:02.436+0000] {processor.py:161} INFO - Started process (PID=62133) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:56:02.438+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:56:02.441+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:56:02.440+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:56:02.528+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:56:02.523+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:56:02.530+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:56:02.566+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.135 seconds
[2024-04-13T00:56:32.708+0000] {processor.py:161} INFO - Started process (PID=62189) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:56:32.710+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:56:32.715+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:56:32.712+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:56:32.810+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:56:32.803+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:56:32.814+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:56:32.842+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.140 seconds
[2024-04-13T00:57:03.226+0000] {processor.py:161} INFO - Started process (PID=62244) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:57:03.228+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:57:03.230+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:57:03.230+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:57:03.302+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:57:03.296+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:57:03.305+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:57:03.331+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.110 seconds
[2024-04-13T00:57:33.475+0000] {processor.py:161} INFO - Started process (PID=62299) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:57:33.476+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:57:33.479+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:57:33.479+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:57:33.558+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:57:33.552+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:57:33.560+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:57:33.586+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.116 seconds
[2024-04-13T00:58:04.190+0000] {processor.py:161} INFO - Started process (PID=62360) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:58:04.191+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:58:04.194+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:58:04.194+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:58:04.262+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:58:04.255+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:58:04.264+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:58:04.287+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.104 seconds
[2024-04-13T00:58:34.427+0000] {processor.py:161} INFO - Started process (PID=62415) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:58:34.428+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:58:34.431+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:58:34.430+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:58:34.498+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:58:34.492+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:58:34.501+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:58:34.528+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.107 seconds
[2024-04-13T00:59:04.682+0000] {processor.py:161} INFO - Started process (PID=62471) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:59:04.684+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:59:04.687+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:59:04.687+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:59:04.764+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:59:04.759+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:59:04.766+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:59:04.792+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.117 seconds
[2024-04-13T00:59:34.889+0000] {processor.py:161} INFO - Started process (PID=62527) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:59:34.891+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T00:59:34.894+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:59:34.893+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:59:34.970+0000] {logging_mixin.py:188} INFO - [2024-04-13T00:59:34.964+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T00:59:34.973+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T00:59:34.996+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.112 seconds
[2024-04-13T01:00:05.068+0000] {processor.py:161} INFO - Started process (PID=62582) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T01:00:05.069+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T01:00:05.072+0000] {logging_mixin.py:188} INFO - [2024-04-13T01:00:05.071+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T01:00:05.150+0000] {logging_mixin.py:188} INFO - [2024-04-13T01:00:05.146+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T01:00:05.152+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T01:00:05.184+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.122 seconds
[2024-04-13T01:00:35.386+0000] {processor.py:161} INFO - Started process (PID=62637) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T01:00:35.387+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T01:00:35.390+0000] {logging_mixin.py:188} INFO - [2024-04-13T01:00:35.389+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T01:00:35.465+0000] {logging_mixin.py:188} INFO - [2024-04-13T01:00:35.458+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T01:00:35.467+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T01:00:35.493+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.113 seconds
[2024-04-13T01:01:05.640+0000] {processor.py:161} INFO - Started process (PID=62692) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T01:01:05.641+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T01:01:05.645+0000] {logging_mixin.py:188} INFO - [2024-04-13T01:01:05.645+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T01:01:05.712+0000] {logging_mixin.py:188} INFO - [2024-04-13T01:01:05.706+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T01:01:05.714+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T01:01:05.741+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.109 seconds
[2024-04-13T01:01:36.611+0000] {processor.py:161} INFO - Started process (PID=62747) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T01:01:36.612+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T01:01:36.615+0000] {logging_mixin.py:188} INFO - [2024-04-13T01:01:36.614+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T01:01:36.693+0000] {logging_mixin.py:188} INFO - [2024-04-13T01:01:36.687+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T01:01:36.695+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T01:01:36.719+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.113 seconds
[2024-04-13T01:02:06.862+0000] {processor.py:161} INFO - Started process (PID=62802) to work on /opt/airflow/dags/dags/habidag.py
[2024-04-13T01:02:06.864+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags/habidag.py for tasks to queue
[2024-04-13T01:02:06.878+0000] {logging_mixin.py:188} INFO - [2024-04-13T01:02:06.878+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dags/habidag.py
[2024-04-13T01:02:07.276+0000] {logging_mixin.py:188} INFO - [2024-04-13T01:02:07.123+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags/habidag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags/habidag.py", line 197, in <module>
    "query": open(f'/home/airflow/gcs/dags/sql/reporte1.sql', 'r').read().format(dataset_name=dataset_name, project_name=project_name),
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/sql/reporte1.sql'
[2024-04-13T01:02:07.284+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags/habidag.py
[2024-04-13T01:02:07.337+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags/habidag.py took 0.489 seconds
