[2024-04-02T22:59:17.754+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: google_sheet_to_bigquery.create_tables_in_bigquery manual__2024-04-02T22:58:34.820473+00:00 [queued]>
[2024-04-02T22:59:17.766+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: google_sheet_to_bigquery.create_tables_in_bigquery manual__2024-04-02T22:58:34.820473+00:00 [queued]>
[2024-04-02T22:59:17.767+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 3
[2024-04-02T22:59:17.793+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): create_tables_in_bigquery> on 2024-04-02 22:58:34.820473+00:00
[2024-04-02T22:59:17.802+0000] {standard_task_runner.py:60} INFO - Started process 1723 to run task
[2024-04-02T22:59:17.806+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'google_sheet_to_bigquery', 'create_tables_in_bigquery', 'manual__2024-04-02T22:58:34.820473+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/dags/habidag.py', '--cfg-path', '/tmp/tmpxxg2x6iq']
[2024-04-02T22:59:17.809+0000] {standard_task_runner.py:88} INFO - Job 21: Subtask create_tables_in_bigquery
[2024-04-02T22:59:17.915+0000] {task_command.py:423} INFO - Running <TaskInstance: google_sheet_to_bigquery.create_tables_in_bigquery manual__2024-04-02T22:58:34.820473+00:00 [running]> on host 84784c125ee0
[2024-04-02T22:59:18.170+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='google_sheet_to_bigquery' AIRFLOW_CTX_TASK_ID='create_tables_in_bigquery' AIRFLOW_CTX_EXECUTION_DATE='2024-04-02T22:58:34.820473+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-02T22:58:34.820473+00:00'
[2024-04-02T22:59:18.174+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dags/habidag.py", line 22, in create_tables_in_bigquery
    create_dataset = BigQueryCreateEmptyDatasetOperator(dataset_id="datalake_anyeli")
NameError: name 'BigQueryCreateEmptyDatasetOperator' is not defined
[2024-04-02T22:59:18.192+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=google_sheet_to_bigquery, task_id=create_tables_in_bigquery, execution_date=20240402T225834, start_date=20240402T225917, end_date=20240402T225918
[2024-04-02T22:59:18.218+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 21 for task create_tables_in_bigquery (name 'BigQueryCreateEmptyDatasetOperator' is not defined; 1723)
[2024-04-02T22:59:18.267+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-02T22:59:18.300+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
