[2024-04-02T20:29:14.620+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: google_sheet_to_bigquery.fetch_data_from_google_sheet scheduled__2024-04-02T19:00:00+00:00 [queued]>
[2024-04-02T20:29:14.654+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: google_sheet_to_bigquery.fetch_data_from_google_sheet scheduled__2024-04-02T19:00:00+00:00 [queued]>
[2024-04-02T20:29:14.658+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-02T20:29:14.719+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): fetch_data_from_google_sheet> on 2024-04-02 19:00:00+00:00
[2024-04-02T20:29:14.735+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'google_sheet_to_bigquery', 'fetch_data_from_google_sheet', 'scheduled__2024-04-02T19:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/dags/habidag.py', '--cfg-path', '/tmp/tmp70ob4360']
[2024-04-02T20:29:14.736+0000] {standard_task_runner.py:60} INFO - Started process 1608 to run task
[2024-04-02T20:29:14.739+0000] {standard_task_runner.py:88} INFO - Job 7: Subtask fetch_data_from_google_sheet
[2024-04-02T20:29:14.913+0000] {task_command.py:423} INFO - Running <TaskInstance: google_sheet_to_bigquery.fetch_data_from_google_sheet scheduled__2024-04-02T19:00:00+00:00 [running]> on host b5525c9d82ca
[2024-04-02T20:29:15.312+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='google_sheet_to_bigquery' AIRFLOW_CTX_TASK_ID='fetch_data_from_google_sheet' AIRFLOW_CTX_EXECUTION_DATE='2024-04-02T19:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-02T19:00:00+00:00'
[2024-04-02T20:29:15.316+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dags/habidag.py", line 11, in fetch_data_from_google_sheet
    import gspread
ModuleNotFoundError: No module named 'gspread'
[2024-04-02T20:29:15.340+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=google_sheet_to_bigquery, task_id=fetch_data_from_google_sheet, execution_date=20240402T190000, start_date=20240402T202914, end_date=20240402T202915
[2024-04-02T20:29:15.368+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 7 for task fetch_data_from_google_sheet (No module named 'gspread'; 1608)
[2024-04-02T20:29:15.391+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-02T20:29:15.431+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
